apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: trial-api-rule
  namespace: default
  labels:
    app: trial
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
    - "trial.b21355b.kyma.ondemand.com" 
  service:
    name: trial-service  
    port: 3000           
  rules:
    - path: /*
      methods: ["GET"]
      noAuth: true
