apiVersion: v1
kind: Service
metadata:
  name: trialapp-service
  namespace: default
spec:
  selector:
    app: trialapp
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer  # 暂时用 ClusterIP，后续可加 Ingress 暴露
