apiVersion: v1
kind: Service
metadata:
  name: nodejs-argo-service
  namespace: default
spec:
  type: ClusterIP  # 或 LoadBalancer 如果需要外部访问
  selector:
    app: nodejs-argo
  ports:
  - port: 3000
    targetPort: 3000
