apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: trialapp-vs
  namespace: default
spec:
  hosts:
  - "trialapp.kyma.ondemand.com"   # 自定义域名，Trial 环境自动提供 HTTPS
  gateways:
  - kyma-system/kyma-gateway       # 默认外部 Gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: trialapp-service        # 你的 Service 名称
        port:
          number: 3000
